version = 1
SPDX-PackageName = "ci-release-tools"
SPDX-PackageSupplier = "<info@kdab.com>"
SPDX-PackageDownloadLocation = "https://www.github.com/KDABLabs/ci-release-tools"

#misc FILES
[[annotations]]
path = [
    ".gitignore",
    "README.md",
    "REUSE.toml",
    "LICENSE.txt",
    ".pre-commit-config.yaml",
    ".pylintrc",
    ".gitmodules",
    "workflows/submodule-bump.yml",
    "workflows/README.md",
    ".github/agents/patch_ci_qt.agent.md",
    "src/build_qt/CMakePresets.json",
    "src/build_qt/patches/qtbase/0001-fix-ubsan.patch",
    "src/build_qt/patches/qtbase/0002-disable-fsanitize-float-divide-by-zero.patch",
    "src/build_qt/patches/qtbase/0003-Export-QDeferredDeleteEvent.patch",
    "src/build_qt/patches/qtdeclarative/0001-fix-build-with-UBSAN.patch",
    "src/build_qt/patches/qtdeclarative/0002-Fix-more-UBSAN-linking.patch",
    "src/build_qt/patches/qtdeclarative/0003-Fix-undefined-behaviour-when-initializing-TextArea.patch",
    "src/build_qt/patches/qtshadertools/0001-Fix-UBSAN-build-due-to-invalid-down-cast.patch",
    "src/build_qt/patches/qtshadertools/0002-Don-t-build-qsb-with-TSAN.patch",
    "src/build_qt/patches/qtwayland/0001-compositor-Avoid-overflow-for-infiniteRegion.patch",
    "src/build_qt/patches/qtsvg/0001-Fix-developer-build-with-UBSAN-enabled.patch"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar√§lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"
